# BUSINESS QUESTIONS 

## 1. What's our most sales product and how much money has get?
## 2.What is the variance in sales volume per product between December and our highest-performing month?
## 3. Which product has the lowest sales and which month?
## 4. Do our sales increase on a bi-weekly basis due to paydays, or does this have no impact on sales?

In [71]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_csv(r"data/Datos_Ventas_Tienda.csv")
df1

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    1/17/2023  Electrónic         7              200         1400
1     9/1/2023  Electrónic         8              200         1600
2    7/29/2023    Juguetes         3               30           90
3    10/4/2023   Alimentos         4               10           40
4    2/28/2023  Electrónic         6              200         1200
..         ...         ...       ...              ...          ...
995  4/27/2023   Alimentos         2               10           20
996   6/9/2023        Ropa        10               50          500
997  8/21/2023   Alimentos         8               10           80
998  3/28/2023  Electrónic         6              200         1200
999   3/7/2023  Electrónic         4              200          800

[1000 rows x 5 columns]

In [45]:
df2 = pd.read_csv(r"data/Datos_Ventas_Tienda2.csv")
df2

         Fecha    Producto  Cantidad  Precio Unitario  Total Venta
0    8/25/2023  Electrónic         5              200         1000
1    8/14/2023   Alimentos         9               10           90
2    8/30/2023        Ropa         6               50          300
3    11/9/2023   Alimentos         2               10           20
4   10/26/2023        Ropa         8               50          400
5    12/1/2023    Juguetes         2               30           60
6    5/16/2023  Electrónic         4              200          800
7     2/9/2023      Libros         1               20           20
8     1/9/2023  Electrónic         2              200          400
9     5/3/2023  Electrónic         6              200         1200
10  11/30/2023  Electrónic         5              200         1000
11  10/26/2023  Electrónic         1              200          200
12   8/22/2023    Juguetes         3               30           90
13    6/5/2023  Electrónic         1              200          200
14   10/2/2023    Juguetes         6               30          180
15   1/25/2023  Electrónic         3              200          600
16   5/20/2023        Ropa         4               50          200
17   4/29/2023   Alimentos         8               10           80
18  12/20/2023        Ropa         2               50          100
19   4/10/2023        Ropa         8               50          400
20   5/19/2023    Juguetes         5               30          150
21    2/3/2023  Electrónic         4              200          800
22    3/4/2023        Ropa         5               50          250
23  11/12/2023    Juguetes         7               30          210
24   5/22/2023      Libros         7               20          140
25  11/19/2023        Ropa         4               50          200
26   7/31/2023   Alimentos         6               10           60
27  10/11/2023        Ropa         6               50          300
28   12/9/2023    Juguetes         4               30          120
29    3/6/2023      Libros         9               20          180
30   3/27/2023   Alimentos         1               10           10
31   4/23/2023        Ropa         9               50          450
32   5/26/2023  Electrónic         6              200         1200
33   1/20/2023    Juguetes         5               30          150
34   3/22/2023   Alimentos         9               10           90
35   2/26/2023      Libros         9               20          180
36   7/30/2023    Juguetes         1               30           30
37  11/18/2023        Ropa         3               50          150
38   6/20/2023      Libros         8               20          160
39    6/6/2023      Libros         3               20           60
40    5/2/2023   Alimentos         5               10           50
41    8/7/2023  Electrónic         9              200         1800
42  11/18/2023    Juguetes         8               30          240
43   1/17/2023    Juguetes         8               30          240
44  10/10/2023      Libros         6               20          120
45   9/11/2023    Juguetes        10               30          300
46    1/3/2023    Juguetes        10               30          300
47   11/7/2023   Alimentos         3               10           30
48   8/20/2023  Electrónic         6              200         1200
49   7/21/2023    Juguetes         3               30           90

## Concat both csv documents and change column names to English

In [5]:
df_combined = pd.concat([df1, df2], ignore_index=True)
names2 = ["Date", "Product","Quantity", "Price Per Unit", "Total"]
df_combined.columns = names2
df_combined

           Date     Product  Quantity  Price Per Unit  Total
0     1/17/2023  Electrónic         7             200   1400
1      9/1/2023  Electrónic         8             200   1600
2     7/29/2023    Juguetes         3              30     90
3     10/4/2023   Alimentos         4              10     40
4     2/28/2023  Electrónic         6             200   1200
...         ...         ...       ...             ...    ...
1045  9/11/2023    Juguetes        10              30    300
1046   1/3/2023    Juguetes        10              30    300
1047  11/7/2023   Alimentos         3              10     30
1048  8/20/2023  Electrónic         6             200   1200
1049  7/21/2023    Juguetes         3              30     90

[1050 rows x 5 columns]

In [6]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1050 non-null   object
 1   Product         1050 non-null   object
 2   Quantity        1050 non-null   int64
 3   Price Per Unit  1050 non-null   int64
 4   Total           1050 non-null   int64
dtypes: int64(3), object(2)
memory usage: 41.1+ KB

## Change Dtype for "Date" column to DateTime

In [8]:
df_combined["Date"] = pd.to_datetime(df_combined["Date"])
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            1050 non-null   datetime64[ns]
 1   Product         1050 non-null   object
 2   Quantity        1050 non-null   int64
 3   Price Per Unit  1050 non-null   int64
 4   Total           1050 non-null   int64
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 41.1+ KB

## 1. Which product has the highest sales volume, and what is the total sales generated?

In [355]:
df_combined ["Month"] = df_combined["Date"].dt.month_name()
df_product_sales = df_combined.groupby("Product")[["Quantity" , "Total"]].sum().sort_values(by = "Total"  , ascending = False)
df_product_sales = df_product_sales.reset_index()
df_product_sales

print(f"The leading product is {df_product_sales.iloc[0]["Product"]} and sold ${df_product_sales.iloc[0]["Total"]} ")

The leading product is Electrónic and sold $244000

## 2.What is the variance in sales volume per product between December and our highest-performing month?

In [371]:
total_december = df_combined[df_combined["Month"] == "December"].groupby(["Month" , "Product"])["Total"].sum().sort_values( ascending =False)
total_december

Month     Product
December  Electrónic    23400
          Ropa           4800
          Juguetes       2490
          Libros         1860
          Alimentos      1010
Name: Total, dtype: int64

In [449]:
highest_month = df_combined.groupby("Month")["Total"].sum().idxmax()
print(f"The month with highest sales is {highest_month}")

The month with highest sales is August

In [457]:
total_august = df_combined[df_combined["Month"] == "August"].groupby(["Month" , "Product"])["Total"].sum().sort_values( ascending =False)
print(f"{total_august}\n")
print(total_december)

Month   Product
August  Electrónic    31200
        Ropa           7300
        Juguetes       2550
        Libros         2440
        Alimentos      1600
Name: Total, dtype: int64

Month     Product
December  Electrónic    23400
          Ropa           4800
          Juguetes       2490
          Libros         1860
          Alimentos      1010
Name: Total, dtype: int64

In [489]:
print(f"The sales in December are lower than August, none of the products reach the sales in August is recommended use more marketing to increase the sales on this special month")

The sales in December are lower than August, none of the products reach the sales in August is recommended use more marketing to increase the sales on this special month

## 3. Which product has the lowest sales and which month?

In [487]:
df_lowest = df_combined.groupby(["Product","Month"])["Total"].sum().sort_values(ascending =True)
type(df_lowest)
print(f"The lowest product is {df_lowest.index[1][0]} had a total sale : {df_lowest.iloc[0]}")

The lowest product is Alimentos had a total sale : 790

## 4. Do our sales increase on a bi-weekly basis due to paydays, or does this have no impact on sales?

In [359]:
df_combined["Payday"] = df_combined["Date"].dt.day.isin([14,15,16]) #Will provide a boolean 
comparative = df_combined.groupby("Payday")["Total"].mean()
print(f"Normal days {comparative[False]:.2f}\n")
print(f"Paydays {comparative[True]:.2f}\n")

impact_in_percent = ((comparative[True] - comparative[False]) / comparative[False]) * 100

print(f"The reflected sales on Paydays have an impact: {impact_in_percent:.2f}%")

Normal days 345.77

Paydays 399.49

The reflected sales on Paydays have an impact: 15.53%